enterprise-search:
  url: http://localhost:3002/api/ws/v1
  username: elastic
  password: changeme

server:
  port: 8081

logging:
  level:
    org:
      elasticsearch:
        externalconnector:
          client: DEBUG
